export const SHIP_DATA = [
    { id: 202, category: 'ships', name: "Small Cargo", icon: "icons/ships/small-cargo-large.jpg", metadata: { cost: { metal: 2000, crystal: 2000, deuterium: 0 } } },
    { id: 203, category: 'ships', name: "Large Cargo", icon: "icons/ships/large-cargo-large.jpg", metadata: { cost: { metal: 6000, crystal: 6000, deuterium: 0 } } },
    { id: 204, category: 'ships', name: "Light Fighter", icon: "icons/ships/light-fighter-large.jpg", metadata: { cost: { metal: 3000, crystal: 1000, deuterium: 0 } } },
    { id: 205, category: 'ships', name: "Heavy Fighter", icon: "icons/ships/heavy-fighter-large.jpg", metadata: { cost: { metal: 6000, crystal: 4000, deuterium: 0 } } },
    { id: 206, category: 'ships', name: "Cruiser", icon: "icons/ships/cruiser-large.jpg", metadata: { cost: { metal: 20000, crystal: 7000, deuterium: 2000 } } },
    { id: 207, category: 'ships', name: "Battleship", icon: "icons/ships/battleship-large.jpg", metadata: { cost: { metal: 45000, crystal: 15000, deuterium: 0 } } },
    { id: 208, category: 'ships', name: "Colony Ship", icon: "icons/ships/colony-ship-large.jpg", metadata: { cost: { metal: 10000, crystal: 20000, deuterium: 10000 } } },
    { id: 209, category: 'ships', name: "Recycler", icon: "icons/ships/recycler-large.jpg", metadata: { cost: { metal: 10000, crystal: 6000, deuterium: 2000 } } },
    { id: 210, category: 'ships', name: "Espionage Probe", icon: "icons/ships/espionage-probe-large.jpg", metadata: { cost: { metal: 0, crystal: 1000, deuterium: 0 } } },
    { id: 211, category: 'ships', name: "Bomber", icon: "icons/ships/bomber-large.jpg", metadata: { cost: { metal: 50000, crystal: 25000, deuterium: 15000 } } },
    { id: 212, category: 'ships', name: "Solar Satellite", icon: "icons/ships/solar-satellite-large.jpg", metadata: { cost: { metal: 0, crystal: 2000, deuterium: 500 } } },
    { id: 213, category: 'ships', name: "Destroyer", icon: "icons/ships/destroyer-large.jpg", metadata: { cost: { metal: 60000, crystal: 50000, deuterium: 15000 } } },
    { id: 214, category: 'ships', name: "Deathstar", icon: "icons/ships/deathstar-large.jpg", metadata: { cost: { metal: 5000000, crystal: 4000000, deuterium: 1000000 } } },
    { id: 215, category: 'ships', name: "Battlecruiser", icon: "icons/ships/battlecruiser-large.jpg", metadata: { cost: { metal: 30000, crystal: 40000, deuterium: 15000 } } },
    { id: 217, category: 'ships', name: "Crawler", icon: "icons/ships/crawler-large.jpg", metadata: { cost: { metal: 2000, crystal: 2000, deuterium: 1000 } } },
    { id: 218, category: 'ships', name: "Reaper", icon: "icons/ships/reaper-large.jpg", metadata: { cost: { metal: 85000, crystal: 55000, deuterium: 20000 } } },
    { id: 219, category: 'ships', name: "Pathfinder", icon: "icons/ships/pathfinder-large.jpg", metadata: { cost: { metal: 8000, crystal: 15000, deuterium: 8000 } } }
];

export const LIFEFORM_SPECIES_DATA = [
    { lifeformId: 1, lifeformName: "Humans", lifeformLevel: 0, lifeformXP: 0, iconPath: "icons/lifeforms/humans-icon-large.jpg" },
    { lifeformId: 2, lifeformName: "Rock’tal", lifeformLevel: 0, lifeformXP: 0, iconPath: "icons/lifeforms/rocktal-icon-large.jpg" },
    { lifeformId: 3, lifeformName: "Mechas", lifeformLevel: 0, lifeformXP: 0, iconPath: "icons/lifeforms/mechas-icon-large.jpg" },
    { lifeformId: 4, lifeformName: "Kaelesh", lifeformLevel: 0, lifeformXP: 0, iconPath: "icons/lifeforms/kaelesh-icon-large.jpg" }
];

export const RESEARCH_DATA = [
    { id: 113, category: 'research', name: "Energy Technology", icon: "" },
    { id: 120, category: 'research', name: "Laser Technology", icon: "" },
    { id: 121, category: 'research', name: "Ion Technology", icon: "" },
    { id: 114, category: 'research', name: "Hyperspace Technology", icon: "" },
    { id: 122, category: 'research', name: "Plasma Technology", icon: "" },
    { id: 115, category: 'research', name: "Combustion Drive", icon: "" },
    { id: 117, category: 'research', name: "Impulse Drive", icon: "" },
    { id: 118, category: 'research', name: "Hyperspace Drive", icon: "" },
    { id: 106, category: 'research', name: "Espionage Technology", icon: "" },
    { id: 108, category: 'research', name: "Computer Technology", icon: "" },
    { id: 124, category: 'research', name: "Astrophysics", icon: "" },
    { id: 123, category: 'research', name: "Intergalactic Research Network", icon: "" },
    { id: 199, category: 'research', name: "Graviton Technology", icon: "" },
    { id: 109, category: 'research', name: "Weapons Technology", icon: "" },
    { id: 110, category: 'research', name: "Shielding Technology", icon: "" },
    { id: 111, category: 'research', name: "Armour Technology", icon: "" }
];

export const DEFENCE_DATA = [
    { id: 401, category: 'defence', name: "Rocket Launcher", icon: "" },
    { id: 402, category: 'defence', name: "Light Laser", icon: "" },
    { id: 403, category: 'defence', name: "Heavy Laser", icon: "" },
    { id: 404, category: 'defence', name: "Gauss Cannon", icon: "" },
    { id: 405, category: 'defence', name: "Ion Cannon", icon: "" },
    { id: 406, category: 'defence', name: "Plasma Turret", icon: "" },
    { id: 407, category: 'defence', name: "Small Shield Dome", icon: "" },
    { id: 408, category: 'defence', name: "Large Shield Dome", icon: "" },
    { id: 502, category: 'defence', name: "Anti-Ballistic Missiles", icon: "" },
    { id: 503, category: 'defence', name: "Interplanetary Missiles", icon: "" }
];

export const BUILDING_DATA = [
    { id: 1, category: 'buildings', name: "Metal Mine", icon: "" },
    { id: 2, category: 'buildings', name: "Crystal Mine", icon: "" },
    { id: 3, category: 'buildings', name: "Deuterium Synthesizer", icon: "" },
    { id: 4, category: 'buildings', name: "Solar Plant", icon: "" },
    { id: 12, category: 'buildings', name: "Fusion Reactor", icon: "" },
    { id: 14, category: 'buildings', name: "Robotics Factory", icon: "" },
    { id: 15, category: 'buildings', name: "Nanite Factory", icon: "" },
    { id: 21, category: 'buildings', name: "Shipyard", icon: "" },
    { id: 22, category: 'buildings', name: "Metal Storage", icon: "" },
    { id: 23, category: 'buildings', name: "Crystal Storage", icon: "" },
    { id: 24, category: 'buildings', name: "Deuterium Tank", icon: "" },
    { id: 31, category: 'buildings', name: "Research Lab", icon: "" },
    { id: 33, category: 'buildings', name: "Terraformer", icon: "" },
    { id: 34, category: 'buildings', name: "Alliance Depot", icon: "" },
    { id: 36, category: 'buildings', name: "Space Dock", icon: "" },
    { id: 41, category: 'buildings', name: "Lunar Base", icon: "" },
    { id: 42, category: 'buildings', name: "Sensor Phalanx", icon: "" },
    { id: 43, category: 'buildings', name: "Jump Gate", icon: "" },
    { id: 44, category: 'buildings', name: "Missile Silo", icon: "" }
];

export const LIFEFORM_RESEARCH_DATA = [
    // Humans Research
    { id: 11201, category: 'lifeformResearch', name: "Intergalactic Envoys", icon: "" },
    { id: 11202, category: 'lifeformResearch', name: "High-Performance Extractors", icon: "" },
    { id: 11203, category: 'lifeformResearch', name: "Fusion Drives", icon: "" },
    { id: 11204, category: 'lifeformResearch', name: "Stealth Field Generator", icon: "" },
    { id: 11205, category: 'lifeformResearch', name: "Orbital Den", icon: "" },
    { id: 11206, category: 'lifeformResearch', name: "Research AI", icon: "" },
    { id: 11207, category: 'lifeformResearch', name: "High-Performance Terraformer", icon: "" },
    { id: 11208, category: 'lifeformResearch', name: "Enhanced Production Technologies", icon: "" },
    { id: 11209, category: 'lifeformResearch', name: "Light Fighter Mk II", icon: "" },
    { id: 11210, category: 'lifeformResearch', name: "Cruiser Mk II", icon: "" },
    { id: 11211, category: 'lifeformResearch', name: "Improved Lab Technology", icon: "" },
    { id: 11212, category: 'lifeformResearch', name: "Plasma Terraformer", icon: "" },
    { id: 11213, category: 'lifeformResearch', name: "Low-Temperature Drives", icon: "" },
    { id: 11214, category: 'lifeformResearch', name: "Bomber Mk II", icon: "" },
    { id: 11215, category: 'lifeformResearch', name: "Destroyer Mk II", icon: "" },
    { id: 11216, category: 'lifeformResearch', name: "Battlecruiser Mk II", icon: "" },
    { id: 11217, category: 'lifeformResearch', name: "Robot Assistants", icon: "" },
    { id: 11218, category: 'lifeformResearch', name: "Supercomputer", icon: "" },

    // Rock’tal Research
    { id: 12201, category: 'lifeformResearch', name: "Volcanic Batteries", icon: "" },
    { id: 12202, category: 'lifeformResearch', name: "Acoustic Scanning", icon: "" },
    { id: 12203, category: 'lifeformResearch', name: "High Energy Pump Systems", icon: "" },
    { id: 12204, category: 'lifeformResearch', name: "Cargo Hold Expansion (Civilian Ships)", icon: "" },
    { id: 12205, category: 'lifeformResearch', name: "Magma-Powered Production", icon: "" },
    { id: 12206, category: 'lifeformResearch', name: "Geothermal Power Plants", icon: "" },
    { id: 12207, category: 'lifeformResearch', name: "Depth Sounding", icon: "" },
    { id: 12208, category: 'lifeformResearch', name: "Ion Crystal Enhancement (Heavy Fighter)", icon: "" },
    { id: 12209, category: 'lifeformResearch', name: "Improved Stellarator", icon: "" },
    { id: 12210, category: 'lifeformResearch', name: "Hardened Diamond Drill Heads", icon: "" },
    { id: 12211, category: 'lifeformResearch', name: "Seismic Mining Technology", icon: "" },
    { id: 12212, category: 'lifeformResearch', name: "Magma-Powered Pump Systems", icon: "" },
    { id: 12213, category: 'lifeformResearch', name: "Ion Crystal Modules", icon: "" },
    { id: 12214, category: 'lifeformResearch', name: "Optimised Silo Construction Method", icon: "" },
    { id: 12215, category: 'lifeformResearch', name: "Diamond Energy Transmitter", icon: "" },
    { id: 12216, category: 'lifeformResearch', name: "Obsidian Shield Reinforcement", icon: "" },
    { id: 12217, category: 'lifeformResearch', name: "Rune Shields", icon: "" },
    { id: 12218, category: 'lifeformResearch', name: "Rock’tal Collector Enhancement", icon: "" },

    // Mechas Research
    { id: 13201, category: 'lifeformResearch', name: "Catalyser Technology", icon: "" },
    { id: 13202, category: 'lifeformResearch', name: "Plasma Drive", icon: "" },
    { id: 13203, category: 'lifeformResearch', name: "Efficiency Module", icon: "" },
    { id: 13204, category: 'lifeformResearch', name: "Depot AI", icon: "" },
    { id: 13205, category: 'lifeformResearch', name: "General Overhaul (Light Fighter)", icon: "" },
    { id: 13206, category: 'lifeformResearch', name: "Automated Transport Lines", icon: "" },
    { id: 13207, category: 'lifeformResearch', name: "Improved Drone AI", icon: "" },
    { id: 13208, category: 'lifeformResearch', name: "Experimental Recycling Technology", icon: "" },
    { id: 13209, category: 'lifeformResearch', name: "General Overhaul (Cruiser)", icon: "" },
    { id: 13210, category: 'lifeformResearch', name: "Slingshot Autopilot", icon: "" },
    { id: 13211, category: 'lifeformResearch', name: "High-Temperature Superconductors", icon: "" },
    { id: 13212, category: 'lifeformResearch', name: "General Overhaul (Battleship)", icon: "" },
    { id: 13213, category: 'lifeformResearch', name: "Artificial Swarm Intelligence", icon: "" },
    { id: 13214, category: 'lifeformResearch', name: "General Overhaul (Battlecruiser)", icon: "" },
    { id: 13215, category: 'lifeformResearch', name: "General Overhaul (Bomber)", icon: "" },
    { id: 13216, category: 'lifeformResearch', name: "General Overhaul (Destroyer)", icon: "" },
    { id: 13217, category: 'lifeformResearch', name: "Experimental Weapons Technology", icon: "" },
    { id: 13218, category: 'lifeformResearch', name: "Mechan General Enhancement", icon: "" },

    // Kaelesh Research
    { id: 14201, category: 'lifeformResearch', name: "Heat Recovery", icon: "" },
    { id: 14202, category: 'lifeformResearch', name: "Sulphide Process", icon: "" },
    { id: 14203, category: 'lifeformResearch', name: "Psionic Network", icon: "" },
    { id: 14204, category: 'lifeformResearch', name: "Telekinetic Tractor Beam", icon: "" },
    { id: 14205, category: 'lifeformResearch', name: "Enhanced Sensor Technology", icon: "" },
    { id: 14206, category: 'lifeformResearch', name: "Neuromodal Compressor", icon: "" },
    { id: 14207, category: 'lifeformResearch', name: "Neuro-Interface", icon: "" },
    { id: 14208, category: 'lifeformResearch', name: "Interplanetary Analysis Network", icon: "" },
    { id: 14209, category: 'lifeformResearch', name: "Overclocking (Heavy Fighter)", icon: "" },
    { id: 14210, category: 'lifeformResearch', name: "Telekinetic Drive", icon: "" },
    { id: 14211, category: 'lifeformResearch', name: "Sixth Sense", icon: "" },
    { id: 14212, category: 'lifeformResearch', name: "Psychoharmoniser", icon: "" },
    { id: 14213, category: 'lifeformResearch', name: "Efficient Swarm Intelligence", icon: "" },
    { id: 14214, category: 'lifeformResearch', name: "Overclocking (Large Cargo)", icon: "" },
    { id: 14215, category: 'lifeformResearch', name: "Gravitation Sensors", icon: "" },
    { id: 14216, category: 'lifeformResearch', name: "Overclocking (Battleship)", icon: "" },
    { id: 14217, category: 'lifeformResearch', name: "Psionic Shield Matrix", icon: "" },
    { id: 14218, category: 'lifeformResearch', name: "Kaelesh Discoverer Enhancement", icon: "" }
];

export const LIFEFORM_BUILDING_DATA = [
    // Humans Buildings
    { id: 11101, category: 'lifeformBuildings', name: "Residential Sector", icon: "" },
    { id: 11102, category: 'lifeformBuildings', name: "Biosphere Farm", icon: "" },
    { id: 11103, category: 'lifeformBuildings', name: "Research Centre", icon: "" },
    { id: 11104, category: 'lifeformBuildings', name: "Academy of Sciences", icon: "" },
    { id: 11105, category: 'lifeformBuildings', name: "Neuro-Calibration Centre", icon: "" },
    { id: 11106, category: 'lifeformBuildings', name: "High Energy Smelting", icon: "" },
    { id: 11107, category: 'lifeformBuildings', name: "Food Silo", icon: "" },
    { id: 11108, category: 'lifeformBuildings', name: "Fusion-Powered Production", icon: "" },
    { id: 11109, category: 'lifeformBuildings', name: "Skyscraper", icon: "" },
    { id: 11110, category: 'lifeformBuildings', name: "Biotech Lab", icon: "" },
    { id: 11111, category: 'lifeformBuildings', name: "Metropolis", icon: "" },
    { id: 11112, category: 'lifeformBuildings', name: "Planetary Shield", icon: "" },

    // Rock’tal Buildings
    { id: 12101, category: 'lifeformBuildings', name: "Meditation Enclave", icon: "" },
    { id: 12102, category: 'lifeformBuildings', name: "Crystal Farm", icon: "" },
    { id: 12103, category: 'lifeformBuildings', name: "Rune Technologium", icon: "" },
    { id: 12104, category: 'lifeformBuildings', name: "Rune Forge", icon: "" },
    { id: 12105, category: 'lifeformBuildings', name: "Oriktorium", icon: "" },
    { id: 12106, category: 'lifeformBuildings', name: "Magma Forge", icon: "" },
    { id: 12107, category: 'lifeformBuildings', name: "Disruption Chamber", icon: "" },
    { id: 12108, category: 'lifeformBuildings', name: "Megalith", icon: "" },
    { id: 12109, category: 'lifeformBuildings', name: "Crystal Refinery", icon: "" },
    { id: 12110, category: 'lifeformBuildings', name: "Deuterium Synthesiser", icon: "" },
    { id: 12111, category: 'lifeformBuildings', name: "Mineral Research Centre", icon: "" },
    { id: 12112, category: 'lifeformBuildings', name: "Advanced Recycling Plant", icon: "" },

    // Mechas Buildings
    { id: 13101, category: 'lifeformBuildings', name: "Assembly Line", icon: "" },
    { id: 13102, category: 'lifeformBuildings', name: "Fusion Cell Factory", icon: "" },
    { id: 13103, category: 'lifeformBuildings', name: "Robotics Research Centre", icon: "" },
    { id: 13104, category: 'lifeformBuildings', name: "Update Network", icon: "" },
    { id: 13105, category: 'lifeformBuildings', name: "Quantum Computer Centre", icon: "" },
    { id: 13106, category: 'lifeformBuildings', name: "Automatised Assembly Centre", icon: "" },
    { id: 13107, category: 'lifeformBuildings', name: "High-Performance Transformer", icon: "" },
    { id: 13108, category: 'lifeformBuildings', name: "Microchip Assembly Line", icon: "" },
    { id: 13109, category: 'lifeformBuildings', name: "Production Assembly Hall", icon: "" },
    { id: 13110, category: 'lifeformBuildings', name: "High-Performance Synthesiser", icon: "" },
    { id: 13111, category: 'lifeformBuildings', name: "Chip Mass Production", icon: "" },
    { id: 13112, category: 'lifeformBuildings', name: "Nano Repair Bots", icon: "" },

    // Kaelesh Buildings
    { id: 14101, category: 'lifeformBuildings', name: "Sanctuary", icon: "" },
    { id: 14102, category: 'lifeformBuildings', name: "Antimatter Condenser", icon: "" },
    { id: 14103, category: 'lifeformBuildings', name: "Vortex Chamber", icon: "" },
    { id: 14104, category: 'lifeformBuildings', name: "Halls of Realisation", icon: "" },
    { id: 14105, category: 'lifeformBuildings', name: "Forum of Transcendence", icon: "" },
    { id: 14106, category: 'lifeformBuildings', name: "Antimatter Convector", icon: "" },
    { id: 14107, category: 'lifeformBuildings', name: "Cloning Laboratory", icon: "" },
    { id: 14108, category: 'lifeformBuildings', name: "Chrysalis Accelerator", icon: "" },
    { id: 14109, category: 'lifeformBuildings', name: "Bio Modifier", icon: "" },
    { id: 14110, category: 'lifeformBuildings', name: "Psionic Modulator", icon: "" },
    { id: 14111, category: 'lifeformBuildings', name: "Ship Manufacturing Hall", icon: "" },
    { id: 14112, category: 'lifeformBuildings', name: "Supra Refractor", icon: "" }
];
